trigger:
- experiment/pipeline

pool:
  vmImage: vs2017-win2016

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  solution: 'EarTrumpet.vs15.sln'
  buildConfiguration: 'Release'
  buildPlatform: 'x86'

steps:
- task: GitVersion@4
  displayName: 'Initialize Git Version'
  inputs:
    updateAssemblyInfo: false

- task: PowerShell@2
  displayName: 'Set build number'
  inputs:
    targetType: inline
    script: |
     Write-Host "##vso[build.updatebuildnumber]$(GitVersion.SemVer)"

- task: CopyFiles@2
  displayName: 'Promote version.txt to build artifact'
  inputs:
    Contents: 'version.txt'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: NuGetToolInstaller@0
  displayName: 'Install NuGet Tooling'

- task: NuGetCommand@2
  displayName: 'Restore NuGet Packages'
  inputs:
    restoreSolution: '$(solution)'

- task: PowerShell@2
  displayName: 'Set Bugsnag API Key'
  inputs:
   targetType: inline
   script: |
     $cfg = Get-Content ".\EarTrumpet\app.config"
     $cfg | ForEach-Object { $_.Replace("{bugsnag.apikey}", "$(bugsnag.apikey)") } | Set-Content ".\EarTrumpet\app.config"

- task: PowerShell@2
  displayName: 'Change publisher for dev packaging'
  inputs:
   targetType: inline
   script: |
    $manifestPath = ".\EarTrumpet.Package\Package.appxmanifest"
    $manifest = [xml](Get-Content $manifestPath)
    $manifest.Package.Identity.Publisher = "CN=File-New-Project, O=File-New-Project, L=Purcellville, S=Virginia, C=US"
    $manifest.Save($manifestPath)

- task: MSBuild@1
  displayName: 'Build EarTrumpet dev packages'
  inputs:
    solution: 'EarTrumpet.Package\\EarTrumpet.Package.wapproj'
    platform: 'x86'
    configuration: '$(buildConfiguration)'
    msbuildArguments: '/p:AppxBundle=Always /p:AppxPackageDir="$(Build.ArtifactStagingDirectory)" /p:AppxPackageSigningEnabled=false /p:UapAppxPackageBuildMode=CI /p:GenerateAppInstallerFile=true /p:AppInstallerUri="https://install.eartrumpet.app/$(Build.SourceBranchName)" /p:AppInstallerUpdateFrequency=1 /p:AppInstallerCheckForUpdateFrequency=OnApplicationRun'
    maximumCpuCount: true

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'Packages'