trigger:
- experiment/pipeline

pool:
  vmImage: vs2017-win2016

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  solution: 'EarTrumpet.vs15.sln'
  buildConfiguration: 'Release'
  buildPlatform: 'x86'

steps:
- task: NuGetToolInstaller@0
  displayName: 'Install NuGet Tooling'

- task: NuGetCommand@2
  displayName: 'Restore NuGet Packages'
  inputs:
    restoreSolution: '$(solution)'

- task: PowerShell@2
  displayName: 'Set Bugsnag API Key'
  inputs:
   targetType: inline
   script: |
     $cfg = Get-Content ".\EarTrumpet\app.config"
     $cfg | ForEach-Object { $_.Replace("{bugsnag.apikey}", "$(bugsnag.apikey)") } | Set-Content ".\EarTrumpet\app.config"

- task: MSBuild@1
  displayName: 'Build EarTrumpet packages'
  inputs:
    solution: 'EarTrumpet.Package\\EarTrumpet.Package.wapproj'
    platform: 'x86'
    configuration: '$(buildConfiguration)'
    msbuildArguments: '/p:AppxBundle=Always /p:AppxPackageDir="$(Build.ArtifactStagingDirectory)" /p:AppxPackageSigningEnabled=false /p:UapAppxPackageBuildMode=CI'
    maximumCpuCount: true

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'Upload'